### ISSUE TITLE
Inconsistencies between the attendance data in TASS DB and what we are receiving through the TASS API

### ISSUE THREAD

**Issue by arinabagele** [TheAlphaSchoolSystemPTYLTD/student-academic-analytics#21]
We have identified an issue with `getStudentAbsences` where some absence records visible in TASS.web are not returned by TASS API. 
If you need more details to reproduce the issue, please contact us at [help@intellischool.co](mailto:help@intellischool.co).

Thank you.

**Comment by scottetass** [comment]
Hi,

We are investigating this issue and hope to have an answer to your question soon.

Regards, Scott

**Comment by scottetass** [comment]
Absence records are only included in the student analytics API if the absence was recorded for an entire period or the absence spans over multiple periods. If a student arrives late to class or leaves
a class early it is not considered for analytics as they were actually present for some part of the period, albeit a few minutes late for arrival or a few minutes early for departure. This is by design for the analytics data.

We will internally review this requirement to determine it's applicability for the Analytics API and how it may be improved.
